import { Product } from './product.model';
export const PRODUCTS: Product[] = [
  {
    productId: 1,
    productName: 'Aviary',
    suitColors: 'red, black',
    faceType: 'standard',
    theme: 'birds',
    backgroundColor: 'white',
    price: 5.99,
    description:
      'Bird lovers from all over flock together to find a copy of this lovely deck',
    pic: '../../../assets/Images/aviary.jpg',
    quantity: 17,
  },
  {
    productId: 2,
    productName: 'Fyrebird',
    suitColors: 'red, black',
    faceType: 'fancy',
    theme: 'birds, myth',
    backgroundColor: 'white',
    price: 6.99,
    description:
      'This deck is a real hot commodity with phoenixes gracing the back and the suit symbols set ablaze',
    pic: '../../../assets/Images/fyrebird.jpg',
    quantity: 450,
  },
  {
    productId: 3,
    productName: 'Dark Mode',
    suitColors: 'blue, green',
    faceType: 'standard',
    theme: 'tech',
    backgroundColor: 'black',
    price: 6.99,
    description:
      'Do white background cards burn your eyes? If so then do we have a deck for you!',
    pic: '../../../assets/Images/darkMode.jpg',
    quantity: 56,
  },
  {
    productId: 4,
    productName: 'Dragon',
    suitColors: 'red, black',
    faceType: 'fancy',
    theme: 'myth',
    backgroundColor: 'white',
    price: 5.99,
    description:
      'Mythical beasts of majesty dawn the backs of these gorgeous cards',
    pic: '../../../assets/Images/dragon.jpg',
    quantity: 77,
  },
  {
    productId: 5,
    productName: 'Riderback - red',
    suitColors: 'red, black',
    faceType: 'standard',
    theme: 'cards',
    backgroundColor: 'white',
    price: 4.99,
    description: 'An all-time classic',
    pic: '../../../assets/Images/redRB.jpg',
    quantity: 100,
  },
  {
    productId: 6,
    productName: 'Riderback - blue',
    suitColors: 'red, black',
    faceType: 'standard',
    theme: 'cards',
    backgroundColor: 'white',
    price: 4.99,
    description: 'An all-time classic',
    pic: '../../../assets/Images/blueRB.jpg',
    quantity: 100,
  },
  {
    productId: 7,
    productName: 'Stargazer',
    suitColors: 'same',
    faceType: 'standard',
    theme: 'space',
    backgroundColor: 'black',
    price: 5.99,
    description:
      'Lovers of the stars unite! These cards will let you see far into the reaches of outer space any time of day',
    pic: '',
    quantity: 33,
  },
  {
    productId: 8,
    productName: 'Stargazer: Sunspot',
    suitColors: 'same',
    faceType: 'standard',
    theme: 'space',
    backgroundColor: 'maroon',
    price: 5.99,
    description:
      'Unlike the actual sun, you can stare at these beauties all day and still retain your sight',
    pic: '../../../assets/Images/stargazerSunspot.jpg',
    quantity: 27,
  },
  {
    productId: 9,
    productName: 'Avengers',
    suitColors: 'red, black',
    faceType: 'fancy',
    theme: 'tv/movies',
    backgroundColor: 'white',
    price: 7.99,
    description: 'Every marvel fans favorite deck',
    pic: '',
    quantity: 15,
  },
  {
    productId: 10,
    productName: 'Archangels',
    suitColors: 'red, black',
    faceType: 'standard',
    theme: '',
    backgroundColor: 'white',
    price: 5.99,
    description: '',
    pic: '../../../assets/Images/archangel.jpg',
    quantity: 10,
  },
  {
    productId: 11,
    productName: 'Majesty',
    suitColors: 'maroon, black',
    faceType: 'fancy',
    theme: 'royalty',
    backgroundColor: 'white',
    price: 7.99,
    description: '',
    pic: '../../../assets/Images/majesty.jpg',
    quantity: 75,
  },
  {
    productId: 12,
    productName: 'Stargazer: Nebula',
    suitColors: 'red, white',
    faceType: 'standard',
    theme: 'space',
    backgroundColor: 'black',
    price: 6.99,
    description: '',
    pic: '../../../assets/Images/stargazerNebula.jpg',
    quantity: 88,
  },
  {
    productId: 13,
    productName: 'Amplified',
    suitColors: 'orange, blue',
    faceType: 'fancy',
    theme: '',
    backgroundColor: 'white',
    price: 5.99,
    description: '',
    pic: '../../../assets/Images/amplified.jpg',
    quantity: 15,
  },
];
